version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017